from __future__ import annotations

from abc import ABC, abstractmethod
from time import perf_counter
from typing import Any, Dict, Optional

import numpy as np
import torch

from minimal_qrl.envs import CommInspectionDubinsUAV2D
from minimal_qrl.gc_agents import GoalConditionedAgentBase


class BaselineController(ABC):
    """Common per-episode interface used by all formal baselines."""

    name = "controller"

    def __init__(self) -> None:
        self.goal_obs: Optional[np.ndarray] = None
        self.seed = 0
        self._episode_diagnostics: Dict[str, Any] = {}

    def begin_episode(
        self,
        env: CommInspectionDubinsUAV2D,
        goal_obs: np.ndarray,
        seed: int,
    ) -> Dict[str, Any]:
        self.goal_obs = np.asarray(goal_obs, dtype=np.float32).copy()
        self.seed = int(seed)
        self._episode_diagnostics = {}
        return {}

    @abstractmethod
    def act(
        self,
        obs: np.ndarray,
        env: CommInspectionDubinsUAV2D,
    ) -> tuple[np.ndarray, Dict[str, Any]]:
        raise NotImplementedError

    def end_episode(self) -> Dict[str, Any]:
        return dict(self._episode_diagnostics)


class PolicyController(BaselineController):
    """Adapter for QRL greedy and goal-conditioned learned policies."""

    def __init__(
        self,
        agent: GoalConditionedAgentBase,
        *,
        name: str,
        static_diagnostics: Optional[Dict[str, Any]] = None,
    ) -> None:
        super().__init__()
        self.agent = agent
        self.name = str(name)
        self.static_diagnostics = dict(static_diagnostics or {})
        self._warmed_up = False

    def begin_episode(
        self,
        env: CommInspectionDubinsUAV2D,
        goal_obs: np.ndarray,
        seed: int,
    ) -> Dict[str, Any]:
        super().begin_episode(env, goal_obs, seed)
        if not self._warmed_up:
            current_obs = env.state_to_observation(env.state).astype(np.float32)
            _ = self.agent.batch_value(current_obs[None, :], self.goal_obs[None, :])
            self._warmed_up = True
        self._episode_diagnostics.update(self.static_diagnostics)
        return dict(self.static_diagnostics)

    def act(
        self,
        obs: np.ndarray,
        env: CommInspectionDubinsUAV2D,
    ) -> tuple[np.ndarray, Dict[str, Any]]:
        del env
        if self.goal_obs is None:
            raise RuntimeError("begin_episode must be called before act")
        device = getattr(self.agent, "device", None)
        if device is not None and torch.device(device).type == "cuda" and torch.cuda.is_available():
            torch.cuda.synchronize(torch.device(device))
        elif device is not None and torch.device(device).type == "mps" and hasattr(torch.mps, "synchronize"):
            torch.mps.synchronize()
        start = perf_counter()
        action = self.agent.act(obs, self.goal_obs, eval_mode=True)
        if device is not None and torch.device(device).type == "cuda" and torch.cuda.is_available():
            torch.cuda.synchronize(torch.device(device))
        elif device is not None and torch.device(device).type == "mps" and hasattr(torch.mps, "synchronize"):
            torch.mps.synchronize()
        elapsed = perf_counter() - start
        return np.asarray(action, dtype=np.float32).reshape(-1), {
            "planning_time_sec": float(elapsed),
        }


def rollout_controller_episode(
    controller: BaselineController,
    env: CommInspectionDubinsUAV2D,
    *,
    episode_seed: int,
    device_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Run one controller on the exact environment task generated by a seed."""

    np.random.seed(int(episode_seed))
    options = {"device_id": str(device_id)} if device_id is not None else None
    obs, reset_info = env.reset(seed=int(episode_seed), options=options)
    goal_obs = env.abstract_goal_observation().astype(np.float32)
    begin_diag = controller.begin_episode(env, goal_obs, int(episode_seed)) or {}

    states = [env.state.copy()]
    actions = []
    rewards = []
    step_infos = []
    action_diagnostics = []
    task_flags = [bool(reset_info.get("task_feasible", False))]
    final_info = dict(reset_info)
    done = False
    truncated = False
    collided = False
    out_of_bounds = False

    while not (done or truncated):
        action, diagnostics = controller.act(obs, env)
        action = np.asarray(action, dtype=np.float32).reshape(-1)
        obs, reward, done, truncated, info = env.step(action)
        info = dict(info)

        actions.append(action.copy())
        rewards.append(float(reward))
        step_infos.append(info)
        action_diagnostics.append(dict(diagnostics or {}))
        states.append(env.state.copy())
        task_flags.append(bool(info.get("task_feasible", False)))
        final_info = info
        collided = collided or bool(info.get("collision", False))
        out_of_bounds = out_of_bounds or bool(info.get("out_of_bounds", False))

    end_diag = controller.end_episode() or {}
    planning_times = [
        float(d.get("planning_time_sec", 0.0))
        for d in action_diagnostics
        if d.get("planning_time_sec") is not None
    ]
    diagnostics = {**begin_diag, **end_diag}
    diagnostics["total_planning_time_sec"] = float(
        diagnostics.get("initial_planning_time_sec", 0.0) + sum(planning_times)
    )
    diagnostics["avg_online_planning_time_sec"] = (
        float(np.mean(planning_times)) if planning_times else 0.0
    )
    initial_planning_time = float(diagnostics.get("initial_planning_time_sec", 0.0))
    diagnostics["first_decision_time_sec"] = initial_planning_time + (
        planning_times[0] if planning_times else 0.0
    )
    diagnostics["planning_time_p95_sec"] = float(np.percentile(planning_times, 95)) if planning_times else 0.0
    diagnostics["planning_time_p99_sec"] = float(np.percentile(planning_times, 99)) if planning_times else 0.0

    return {
        "execution_mode": controller.name,
        "seed": int(episode_seed),
        "states": states,
        "actions": actions,
        "rewards": rewards,
        "step_infos": step_infos,
        "action_diagnostics": action_diagnostics,
        "controller_diagnostics": diagnostics,
        "task_flags": task_flags,
        "success": bool(final_info.get("success", False)),
        "terminated": bool(done),
        "truncated": bool(truncated),
        "num_steps": int(len(actions)),
        "collision": bool(collided),
        "out_of_bounds": bool(out_of_bounds),
        "initial_info": dict(reset_info),
        "final_info": dict(final_info),
        "start": np.asarray(env.start, dtype=np.float32).copy(),
        "abstract_goal_observation": goal_obs.copy(),
        "inspection_target": np.asarray(env.inspection_target, dtype=np.float32).copy(),
        "ground_station": np.asarray(env.ground_station, dtype=np.float32).copy(),
        "device_id": str(env.active_device_id),
        "high_level_events": [],
    }
